# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- main

pool:
  vmImage: 'macos-latest'

steps:
- task: Xcode@5
  displayName: "Build"
  inputs:
    actions: 'build'
    scheme: 'AlpacaNoteFramework'
    sdk: 'iphoneos'
    configuration: 'Debug'
    xcWorkspacePath: 'AlpacaNoteFramework/AlpacaNoteFramework.xcodeproj'
    xcodeVersion: 'default'

- task: Xcode@5
  displayName: "Test Framework"
  inputs:
    actions: 'test'
    scheme: 'AlpacaNoteFramework'
    sdk: 'iphoneos'
    configuration: 'Debug'
    xcWorkspacePath: 'AlpacaNoteFramework/AlpacaNoteFramework.xcodeproj'
    xcodeVersion: 'default'
